services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: nifreebie
      POSTGRES_PASSWORD: nis150905
      POSTGRES_DB: PasteBin

  minio:
    image: quay.io/minio/minio:RELEASE.2025-03-12T18-04-18Z
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
        MINIO_ROOT_USER: minioAccessKey
        MINIO_ROOT_PASSWORD: minioSecretKey
    command: server --console-address ":9001" /data
    volumes:
      - ./minio_data:/data

  redis:
    image: redis:7.0-alpine
    container_name: pastebin-redis
    ports:
      - "6379:6379"
    command: [ "redis-server", "--appendonly", "yes" ]
