app:
  min-hash-count: 10
  cache-ttl-minutes: 10

spring:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  data:
    redis:
      host: localhost
      port: 6379
  config:
    import: optional:file:D:\pastebin\.env[.properties]

minio:
  endpoint: ${MINIO_ENDPOINT}
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  bucket: ${MINIO_BUCKET}

error:
  handling:
    http-status-in-json-response: true
    exception-logging: NO_LOGGING
    full-stacktrace-http-statuses: 5xx
    log-levels:
      5xx: ERROR
    codes:
      NodeAttributeTypeUnique: NODE_ATTRIBUTE_TYPE_UNIQUE